# Generated by Django 5.0.4 on 2024-05-02 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Родитель',
            },
        ),
        migrations.CreateModel(
            name='Girls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('time', models.DateTimeField(verbose_name='Время')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='girls', to='base.parent', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Девочка',
            },
        ),
        migrations.CreateModel(
            name='Boys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('time', models.DateTimeField(verbose_name='Время')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boys', to='base.parent', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Мальчик',
            },
        ),
    ]
